In [ ]:
# Question no:1 part(a)
class Shape(object):
    def __init__(self, length, width):        
        self.length = length
        self.width = width
    def calculate_area(self):
        return self.length * self.width
class Circle(Shape):
    def __init__(self, radius):
        super().__init__(radius, radius)  # Assuming width is the same as length for a circle
        self.radius = radius
    def calculate_circumference(self):
        return 2 * 3.14 * self.radius
while True:
    print("\nMenu:")
    print("1. Create a regular shape")
    print("2. Create a circle")
    print("3. Exit")
    choice = input("Enter your choice (1, 2, or 3): ")
    if choice == '1':
        length = float(input("Enter length of the Shape: "))
        width = float(input("Enter width of the Shape: "))
        obj = Shape(length, width)
        print("Area of the Shape:", obj.calculate_area())
    elif choice == '2':
        radius = float(input("Enter radius of the Circle: "))
        obj = Circle(radius)
        print("Circumference of the Circle:", obj.calculate_circumference())
    elif choice == '3':
        print("Exit (^_^)| Bye!")
        break
    else:
        print("Invalid choice. Please enter 1, 2, or 3.")

# Question no :1 Part (b)

In [2]:
class BankAccount(object):
    def __init__(self, initial_balance):
        self.__balance = initial_balance
    def deposit(self, deposit_amount):
        if deposit_amount > 0:
            self.__balance += deposit_amount
            print(f"Deposited PKR:{deposit_amount}. New balance is PKR:{self.__balance}")
        else:
            print("Invalid deposit amount please enter a positive value.")
    def withdraw(self, withdraw_amount):
        if withdraw_amount <= 0:
            print("Invalid input for Withdraw")
        elif withdraw_amount > self.__balance:
            print("Insufficient balance for Withdraw")
        else:
            self.__balance -= withdraw_amount
            print(f"Withdrew PKR:{withdraw_amount}. New balance: PKR:{self.__balance}")
    def current_balance(self):
        return self.__balance
balance = float(input("Enter your initial balance: "))
bank_account = BankAccount(balance)
while True:
    print("\nMenu:")
    print("1. Deposit money")
    print("2. Withdraw money")
    print("3. Check current balance")
    print("4. Exit")
    choice = input("Enter your choice (1, 2, 3, or 4): ")
    if choice == '1':
        deposit_amount = float(input("Enter the deposit amount: "))
        bank_account.deposit(deposit_amount)
    elif choice == '2':
        withdraw_amount = float(input("Enter the withdrawal amount: "))
        bank_account.withdraw(withdraw_amount)
    elif choice == '3':
        print("Current balance:", bank_account.current_balance())
    elif choice == '4':
        print("Exit (^_^)| Goodbye!")
        break
    else:
        print("Invalid choice. Please enter 1, 2, 3, or 4.")

Enter your initial balance: 50000

Menu:
1. Deposit money
2. Withdraw money
3. Check current balance
4. Exit
Enter your choice (1, 2, 3, or 4): 1
Enter the deposit amount: 500
Deposited PKR:500.0. New balance is PKR:50500.0

Menu:
1. Deposit money
2. Withdraw money
3. Check current balance
4. Exit
Enter your choice (1, 2, 3, or 4): 500
Invalid choice. Please enter 1, 2, 3, or 4.

Menu:
1. Deposit money
2. Withdraw money
3. Check current balance
4. Exit
Enter your choice (1, 2, 3, or 4): 3
Current balance: 50500.0

Menu:
1. Deposit money
2. Withdraw money
3. Check current balance
4. Exit
Enter your choice (1, 2, 3, or 4): 2
Enter the withdrawal amount: 500
Withdrew PKR:500.0. New balance: PKR:50000.0

Menu:
1. Deposit money
2. Withdraw money
3. Check current balance
4. Exit
Enter your choice (1, 2, 3, or 4): 2
Enter the withdrawal amount: 500
Withdrew PKR:500.0. New balance: PKR:49500.0

Menu:
1. Deposit money
2. Withdraw money
3. Check current balance
4. Exit
Enter your choice (1, 2, 3

# Question 1:Part(c)

In [28]:
class Person(object):
    def __init__(self, name, age=None):
        self.name = name
        self.age = age
    def display(self):
        if self.age is not None:
            print(f"Name of the person is {self.name} and Age is {self.age}")
        else:
            print(f"Name of the person is {self.name} and Age is not given")
Name = input("Enter name of the person: ")
Age = int(input("Enter age of the person (press Enter if not specified): ") or 21)
A = Person(Name, Age)
A.display()

Enter name of the person: Hanan
Enter age of the person (press Enter if not specified): 20
Name of the person is Hanan and Age is 20


# Question no:1 Part(d)

In [ ]:
class Shape(object):
    def __init__(self, length, width):
        self.length = length
        self.width = width
    def area(self):
        return self.length * self.width
class Circle(Shape):
    def __init__(self, radius):
        super().__init__(radius, radius)  # Assuming width is the same as length for a circle
        self.radius = radius
    def area(self):
        return 3.14 * self.radius * self.radius  # Area of a circle
    def circumference(self):
        return 2 * 3.14 * self.radius
while True:
    print("\nMenu:")
    print("1. Calculate area of a rectangle")
    print("2. Calculate area of a circle")
    print("3. Exit")
    choice = input("Enter your choice (1, 2, or 3): ")
    if choice == '1':
        length = float(input("Enter length of the rectangle: "))
        width = float(input("Enter width of the rectangle: "))
        rectangle = Shape(length, width)
        print(f"Area of the rectangle: {rectangle.area()}")
    elif choice == '2':
        radius = float(input("Enter radius of the circle: "))
        circle = Circle(radius)
        print(f"Area of the circle: {circle.area()}")
        print(f"Circumference of the circle: {circle.circumference()}")
    elif choice == '3':
        print("Exit (^_^)| Goodbye!")
        break
    else:
        print("Invalid choice. Please enter 1, 2, or 3.")


Menu:
1. Calculate area of a rectangle
2. Calculate area of a circle
3. Exit


# Question 2:

In [3]:
class Vehicle(object):
    def __init__(self, brand):
        self.brand = brand
    def display(self):
        print(f"Brand of this vehicle is {self.brand}:")
class Car(Vehicle):
    def start_engine(self):
        print("Starting the Engine:")
class Bicycle(Vehicle):
    def pedal(self):
        print("Pedaling the bicycle")
class HybridCar(Car, Bicycle):
    def __init__(self, brand, fuel_type):
        super().__init__(brand)
        self.fuel_type = fuel_type
        self.battery_charge = 100 
    def display(self):
        print(f"Hybrid car of Fuel-Type {self.fuel_type}, Brand is {self.brand}, and Battery Charge: {self.battery_charge}%")
    def recharge_battery(self, amount):
        self.battery_charge = min(100, self.battery_charge + amount)
        print(f"Battery recharged. Current charge: {self.battery_charge}%")
    def drive(self, distance):
        if self.battery_charge > 0:
            print(f"Driving {distance} miles on electricity.")
            self.battery_charge = max(0, self.battery_charge - 10 * distance)  # Updated to subtract charge
            print(f"Battery charge remaining: {self.battery_charge}%")
        else:
            print("Battery is empty. Starting the engine.")
            super().start_engine()
while True:
    print("\nMenu:")
    print("1. Start Car Engine")
    print("2. Pedal Bicycle")
    print("3. Drive Hybrid Car")
    print("4. Recharge Hybrid Car Battery")
    print("5. Display Vehicle Information")
    print("6. Exit")
    choice = input("Enter your choice between 1 to 6: ")
    if choice == '1':
        car = Car("Toyota")
        car.start_engine()
    elif choice == '2':
        bicycle = Bicycle("Schwinn")
        bicycle.pedal()
    elif choice == '3':
        hybrid_car = HybridCar("Toyota Prius", "electricity and gasoline")
        distance = float(input("Enter the distance to drive (in miles): "))
        hybrid_car.drive(distance)
    elif choice == '4':
        hybrid_car = HybridCar("Toyota Prius", "electricity and gasoline")
        amount = int(input("Enter the amount to recharge the battery (in percentage): "))
        hybrid_car.recharge_battery(amount)
    elif choice == '5':
        hybrid_car = HybridCar("Toyota Prius", "electricity and gasoline")
        hybrid_car.display()
    elif choice == '6':
        print("Exiting the program. Goodbye!")
        break
    else:
        print("Invalid choice. Please enter a number from 1 to 6.")


Menu:
1. Start Car Engine
2. Pedal Bicycle
3. Drive Hybrid Car
4. Recharge Hybrid Car Battery
5. Display Vehicle Information
6. Exit
Enter your choice between 1 to 6: 1
Starting the Engine:

Menu:
1. Start Car Engine
2. Pedal Bicycle
3. Drive Hybrid Car
4. Recharge Hybrid Car Battery
5. Display Vehicle Information
6. Exit
Enter your choice between 1 to 6: 2
Pedaling the bicycle

Menu:
1. Start Car Engine
2. Pedal Bicycle
3. Drive Hybrid Car
4. Recharge Hybrid Car Battery
5. Display Vehicle Information
6. Exit


KeyboardInterrupt: Interrupted by user

# Question 3:(a)

In [4]:
import numpy as np
arr_1d = []
for i in range(20):
    num = input(f"Enter element at index {i + 1}: ")
    arr_1d.append(num)
# Convert the list to a NumPy array
arr_1d = np.array(arr_1d)
# Reshape the 1D array into a 2D array with 4 rows and 5 columns
arr_2d = arr_1d.reshape(4, 5)
print("Original 1D array:")
print(arr_1d)
print("\nReshaped 2D array:")
print(arr_2d)

KeyboardInterrupt: Interrupted by user

# Question no:3 Part(B)

In [6]:
import numpy as np
random_array = np.random.randint(0, 100,20)
max_value = np.max(random_array)
min_value = np.min(random_array)
print("Generated random array is:")
print(random_array)
print("\nMaximum value in the array is :", max_value)
print("Minimum value in the array is :", min_value)

Generated random array is:
[ 0 75 50 20 58 18 83 61  4 36 69  2 14 78 39 31  4 82 13 20]

Maximum value in the array is : 83
Minimum value in the array is : 0


# Question no 3:Part(C)

In [8]:
mask = random_array > 50
filtered_values = random_array[mask]
# Display the original array, mask and filtered values
print("Original array:")
print(random_array)
print("\nMask for values greater than 50:")
print(mask)
print("\nFiltered values greater than 50:")
print(filtered_values)

Original array:
[ 0 75 50 20 58 18 83 61  4 36 69  2 14 78 39 31  4 82 13 20]

Mask for values greater than 50:
[False  True False False  True False  True  True False False  True False
 False  True False False False  True False False]

Filtered values greater than 50:
[75 58 83 61 69 78 82]


# Question no:3 Part(D)

In [45]:
"""Broadcasting in NumPy is a powerful feature that allows you to perform operations on arrays of different shapes.
When you operate on two arrays of different shapes NumPy automatically broadcasts the smaller array to match the dimensions of the larger array.
This means that the smaller array is effectively duplicated along the missing dimensions.
Broadcasting is a very efficient way to perform element wise operations on arrays, and it can often save you a lot of time and code compared to using explicit loops.
However it is important to understand the rules of broadcasting in order to use it effectively.
Rules of Broadcasting
There are two main rules of broadcasting in NumPy:
Dimensions must be compatible. The two arrays must have the same number of dimensions except for trailing dimensions that are 1 in the smaller array.
For example: a 2D array can be broadcast with a 1D array, but a 2D array cannot be broadcast with a 3D array.
Shape must be compatible.
The shapes of the two arrays must be compatible, which means that the corresponding dimensions must have the same size or one of the sizes must be 1.
For example, a (3, 4) array can be broadcast with a (1, 4) array, but a (3, 4) arraycannot be broadcast with a (2, 4) array.""" 
#Code Example
import numpy as np
a = np.array([1, 2, 3])
b = 5
c = a + b
print(c)

[6 7 8]


# Question no:3 Part (E)

In [48]:
import numpy as np
Array = np.array([2, 4, 6, 8, 10])
# Square every element in the array
Doubled_Array =Array ** 2#store square of array into another array
print("Original array is :",Array)
print("Squared array is :", Doubled_Array)

Original array is : [ 2  4  6  8 10]
Squared array is : [  4  16  36  64 100]


# Question 4: Part (A)

In [13]:
import pandas as pd 
df = pd.read_csv("data.csv")
# Display the first 5 rows by default in the DataFrame
print("First 5 rows of the dataset:")
print(df.head())

First 5 rows of the dataset:
  Series_reference   Period  Data_value Suppressed STATUS
0      BDCQ.SEA1AA  2011.06     80078.0        NaN      F
1      BDCQ.SEA1AA  2011.09     78324.0        NaN      F
2      BDCQ.SEA1AA  2011.12     85850.0        NaN      F
3      BDCQ.SEA1AA  2012.03     90743.0        NaN      F
4      BDCQ.SEA1AA  2012.06     81780.0        NaN      F


# Question 4: Part (B)

In [11]:
import pandas as pd
Data = pd.read_csv("students data.csv")
df = pd.DataFrame(Data)
print("Original Dataset is:\n",df)
# Filter and select rows where the Age column is greater than 30
filtered_df = df[df['Age'] > 30]
print("\nRows where Age is greater than 30:")
print(filtered_df)

Original Dataset is:
        Name   Age   GPA
0      John  17.9  2.71
1      Jane  18.1  3.73
2     Sarah  17.6  2.64
3     Frank  32.1  3.68
4      Mike  18.2  3.46
5  Jennifer  35.0  4.24
6   Jessica  37.3   NaN
7      Fred  19.2  2.54
8       Bob  34.0  3.24

Rows where Age is greater than 30:
       Name   Age   GPA
3     Frank  32.1  3.68
5  Jennifer  35.0  4.24
6   Jessica  37.3   NaN
8       Bob  34.0  3.24


# Question 4: Part (C)

In [18]:
import pandas as pd
Data = pd.read_csv("100 Sales Records.csv")
df = pd.DataFrame(Data)
# Group the data by the Region column and calculate total sales in each region
total_sales = df.groupby('Region')['Sales'].sum()
print("Total sales in each region:")
print(total_sales)

Total sales in each region:
Region
Asia                                  59967
Australia and Oceania                 68325
Central America and the Caribbean     35771
Europe                                98117
Middle East and North Africa          48678
North America                         19143
Sub-Saharan Africa                   177503
Name: Sales, dtype: int64


# Question 4: Part(D)

In [2]:
import pandas as pd
#Data Frame 1
customer_data = {
    'CustomerID': [1, 2, 3, 4, 5],
    'Name': ['Hanan', 'Manan', 'Taimoor', 'Abdullah', 'Qasim']
}
#Data Frame 2
order_data = {
    'OrderID': [101, 102, 103, 104, 105],
    'CustomerID': [1, 2, 3, 4, 5]
}
customer_df = pd.DataFrame(customer_data)
order_df = pd.DataFrame(order_data)
# Display the customer DataFrame
print("Customer DataFrame:")
print(customer_df)
# Display the order DataFrame
print("\nOrder DataFrame:")
print(order_df)
# Perform an inner join to combine data based on the CustomerID column
merged_df = pd.merge(customer_df, order_df, on='CustomerID', how='inner')
# Display the result
print("\nMerged DataFrame:")
print(merged_df)

Customer DataFrame:
   CustomerID      Name
0           1     Hanan
1           2     Manan
2           3   Taimoor
3           4  Abdullah
4           5     Qasim

Order DataFrame:
   OrderID  CustomerID
0      101           1
1      102           2
2      103           3
3      104           4
4      105           5

Merged DataFrame:
   CustomerID      Name  OrderID
0           1     Hanan      101
1           2     Manan      102
2           3   Taimoor      103
3           4  Abdullah      104
4           5     Qasim      105
