In [81]:
from numpy import*
from pandas import*
array_1=random.randint(1,10,(4,4))
array_2=random.randint(1,10,(4,4))
array_3=(array_1*array_2)
print("multilpication Array :\n",array_3)    

multilpication Array :
 [[16 49 16 54]
 [ 9 27 30 35]
 [ 6 15  9 14]
 [63 16  5 12]]


In [57]:
sales_data=DataFrame({'Product':['Head phones','keyboard','Mouse','phone','graphic card'],'Quantity':[2,20,3,4,5],'Price':[75,71,33,24,32]})
print(sales_data)
sales_data['Total Sales']=sales_data['Quantity']*sales_data['Price']
print("Total Sales",sales_data)
print("sorted data is\n",sorted(sales_data))

        Product  Quantity  Price
0   Head phones         2     75
1      keyboard        20     71
2         Mouse         3     33
3         phone         4     24
4  graphic card         5     32
Total Sales         Product  Quantity  Price  Total Sales
0   Head phones         2     75          150
1      keyboard        20     71         1420
2         Mouse         3     33           99
3         phone         4     24           96
4  graphic card         5     32          160
sorted data is
 ['Price', 'Product', 'Quantity', 'Total Sales']


In [62]:
df=DataFrame({'Name':['hanan','hamza','nadeem','faisal','usama'],'Age':[21,20,32,24,25],'Salary':[75000,71000,33000,24000,32000]})
print(df)
df["Bonus"]=random.randint(1000,5000)
print("After adding bonus :\n",df)
df["total Earning"]=df["Salary"]+df["Bonus"]
print("New Data Frame is:\n",df)

     Name  Age  Salary
0   hanan   21   75000
1   hamza   20   71000
2  nadeem   32   33000
3  faisal   24   24000
4   usama   25   32000
After adding bonus :
      Name  Age  Salary  Bonus
0   hanan   21   75000   1153
1   hamza   20   71000   1153
2  nadeem   32   33000   1153
3  faisal   24   24000   1153
4   usama   25   32000   1153
New Data Frame is:
      Name  Age  Salary  Bonus  total Earning
0   hanan   21   75000   1153          76153
1   hamza   20   71000   1153          72153
2  nadeem   32   33000   1153          34153
3  faisal   24   24000   1153          25153
4   usama   25   32000   1153          33153


In [77]:
class Matrix:
    def __init__(self,arr1,arr2):
        self.arr1=arr1
        self.arr2=arr2
    def __add__(self): 
        return self.arr1+self.arr2
    def display(self):
        print("sum of two matrixes are :",self.arr3)
arr1=random.randint(1,10,(2,2))
arr2=random.randint(1,10,(2,2))
A=Matrix(arr1,arr2)
B=matrix(arr1,arr2)
print(A+B)
C.display()

TypeError: Cannot construct a dtype from an array