In [16]:
from numpy import*
v = array([[1,2],[1,2],[1,2]],dtype=complex)
v

array([[1.+0.j, 2.+0.j],
       [1.+0.j, 2.+0.j],
       [1.+0.j, 2.+0.j]])

In [20]:
v=arange(-1,1,0.1)
v

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

In [7]:
from numpy import*
x, y = mgrid[0:5, 0:4]
x


array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4]])

In [8]:
y

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [13]:
x=logspace(0,10,10,base=15)
x

array([1.00000000e+00, 2.02660013e+01, 4.10710808e+02, 8.32346575e+03,
       1.68683368e+05, 3.41853734e+06, 6.92800821e+07, 1.40403023e+09,
       2.84540785e+10, 5.76650391e+11])

In [19]:
import numpy as py
x=py.linspace(-4,4,9)
y=py.linspace(-5,5,11)
x_1,y_1=py.meshgrid(x,y)
x_1
y_1

array([[-5., -5., -5., -5., -5., -5., -5., -5., -5.],
       [-4., -4., -4., -4., -4., -4., -4., -4., -4.],
       [-3., -3., -3., -3., -3., -3., -3., -3., -3.],
       [-2., -2., -2., -2., -2., -2., -2., -2., -2.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.]])

In [32]:
from numpy import random
random.rand(1,10)

array([[0.39869056, 0.03313319, 0.61743465, 0.28531534, 0.50156595,
        0.05477468, 0.17995279, 0.25641017, 0.15566185, 0.25616064]])

In [37]:
diag([1,2,3,4],k=-5)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0]])

In [40]:
a=matrix([[1,2,3],[4,5,6],[7,8,9]])
diag(a,-1)


array([4, 8])

In [42]:
zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
!head stockholm_td_adj.dat

'head' is not recognized as an internal or external command,
operable program or batch file.


In [48]:
A = array([[n+m*10 for n in range(5)] for m in range(5)])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [50]:
A[1:4:1, 1:3:1]

array([[11, 12],
       [21, 22],
       [31, 32]])

In [3]:
import numpy as np
  
# matrix creation by array input 
a = np.matrix([[1, 21, 30],  
                 [63 ,434, 3],  
                 [54, 54, 56]]) 
  
print("Main Diagonal elements : \n", np.diag(a), "\n") 
  
print("Diagonal above main diagonal : \n", np.diag(a, 3), "\n") 
  
print("Diagonal below main diagonal : \n", np.diag(a, -3)) 

Main Diagonal elements : 
 [  1 434  56] 

Diagonal above main diagonal : 
 [] 

Diagonal below main diagonal : 
 []


In [3]:
from numpy import*
M = array([[1, 2], [3, 4]], dtype=complex)

M

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [6]:
x=arange(10,200,10)
x

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190])

In [13]:
x, y = mgrid[1:5, 1:4]
y

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [19]:
a=arange(-1,10,1)
a


array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [18]:
b=linspace(-4,4,9)
b

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [24]:
n_1,n_2=meshgrid(a,b)
print("n_1",n_1)
print("n_2",n_2)

n_1 [[-1  0  1  2  3  4  5  6  7  8  9]
 [-1  0  1  2  3  4  5  6  7  8  9]
 [-1  0  1  2  3  4  5  6  7  8  9]
 [-1  0  1  2  3  4  5  6  7  8  9]
 [-1  0  1  2  3  4  5  6  7  8  9]
 [-1  0  1  2  3  4  5  6  7  8  9]
 [-1  0  1  2  3  4  5  6  7  8  9]
 [-1  0  1  2  3  4  5  6  7  8  9]
 [-1  0  1  2  3  4  5  6  7  8  9]]
n_2 [[-4. -4. -4. -4. -4. -4. -4. -4. -4. -4. -4.]
 [-3. -3. -3. -3. -3. -3. -3. -3. -3. -3. -3.]
 [-2. -2. -2. -2. -2. -2. -2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  4.  4.  4.]]


In [32]:
random.randn(1,10)

array([[-0.34917377, -0.34856962, -0.22692314,  0.83864176, -0.47891945,
        -0.18889118, -1.39931777,  0.01737076,  0.54347262,  0.21869616]])

In [50]:
a = matrix([[1, 21, 30],  
                 [63 ,434, 3],  
                 [54, 12, 56]]) 
a

matrix([[  1,  21,  30],
        [ 63, 434,   3],
        [ 54,  12,  56]])

In [59]:
ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [62]:
data = genfromtxt('stockholm_td_adj.dat')
data.shape


(77431, 7)

In [65]:
fig, ax = plt.subplots(figsize=(14,4))
ax.plot(data[:,0]+data[:,1]/12.0+data[:,2]/365, data[:,5])
ax.axis('tight')
ax.set_title('tempeatures in Stockholm')
ax.set_xlabel('year')
ax.set_ylabel('temperature (C)');

NameError: name 'plt' is not defined

In [68]:
savetxt("random-matrix.csv", M)
savetxt("random-matrix.csv", M, fmt='%.5f')
load("random-matrix.npy")

array([[0.11656766, 0.20767999, 0.25591583],
       [0.33627604, 0.18221333, 0.70731519],
       [0.28520098, 0.87565207, 0.47160983]])

In [83]:
M[1,1]=1
M

array([[1.+0.j, 2.+0.j],
       [2.+0.j, 1.+0.j]])

In [98]:
A=array([i for i in range(5)]for m in range(5))
print(A)
A_transposed = [[row[i] for row in A] for i in range(len(A[0]))]
for row in A_transposed:
    print(row)

<generator object <genexpr> at 0x000001D6F0BCADC0>


IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [124]:
A = array([[n+m*10 for n in range(5)] for m in range(5)])
A
row_indices = [1, 2, 3 ]
A[row_indices]

AttributeError: 'list' object has no attribute 'take'

In [108]:
B = array([n for n in range(5)])
B
row_mask = array([True, False, True, False, False])
B[row_mask]

array([0, 1, 1])

In [112]:
x = arange(0, 10, 0.5)
x
mask = (5 < x) * (x < 7.5)

mask


array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [113]:
indices = where(mask)

indices

(array([11, 12, 13, 14], dtype=int64),)

In [119]:
A
diag(A,-1)


array([10, 21, 32, 43])

In [126]:
aa= [1, 0, 1, 0,1]
bb = [[-1,-2,-3,-4,-6], [15,25,35,55,66]]

choose(aa, bb)

array([15, -2, 35, -4, 66])

In [133]:
v1 = arange(0, 5)
v1
dot(v1,v1)

array([0, 1, 2, 3, 4])

In [146]:
ar1 = array([[1, 3], [2, 9]])
ar2 = array([[5, 6], [8, 0]])
result = tensordot(ar1, ar2, axes=1)
result

array([[29,  6],
       [82, 12]])

In [148]:
x = array([[1,2],[3,4]])
#AX = B => X = A-1 B
y = linalg.inv(x) 
print (x)
print (y)
print (dot(x,y))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [163]:
from pandas import*
from numpy import*
data=[2,4,1,9]
labels=['A','B','C',2]
dataSeries=Series(data=data,index=labels)
dataSeries


A    2
B    4
C    1
2    9
dtype: int64

In [168]:
idx=['a','c']
print(dataSeries[['A','C']])

A    2
C    1
dtype: int64


In [170]:
print (dataSeries[dataSeries<5].index)

Index(['A', 'B', 'C'], dtype='object')


In [171]:
print(dataSeries*2)

A     4
B     8
C     2
2    18
dtype: int64


In [173]:
print (exp(dataSeries))

A       7.389056
B      54.598150
C       2.718282
2    8103.083928
dtype: float64


In [178]:
sdata={'Ohio':3500 , 'Texas':7100 , 'Oregon': 1600 , 'Utah': 5000 }
ssdata=Series(sdata)
print (sdata)
print(ssdata)

SyntaxError: expression expected after dictionary key and ':' (797628.py, line 1)

In [189]:
import pandas as pd
# Create a Pandas Series 's' with some data
s = pd.Series([1, 2, 3, None, 5, None])
# Check for missing values in 's'
missing_values = s.notnull()
print(missing_values)

0     True
1     True
2     True
3    False
4     True
5    False
dtype: bool


In [190]:
s/ssdata

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
5        NaN
Ohio     NaN
Oregon   NaN
Texas    NaN
Utah     NaN
dtype: float64

In [198]:
data={
    'state':["Pakistan","India","Iran"],
    'year':[2000,2001,2002],
    'Pop':[1.5,1.7,3.6]
}
dataDF=DataFrame(data)
dataDF

state  year  Pop
0  Pakistan  2000  1.5
1     India  2001  1.7
2      Iran  2002  3.6

In [200]:
dataDF=DataFrame(data,columns=['year','state','Pop'])
dataDF

year     state  Pop
0  2000  Pakistan  1.5
1  2001     India  1.7
2  2002      Iran  3.6

In [208]:
data={
        'state': ['Ohio','Ohio','Ohio','Nevada','Nevada'],
        'year': [2000,2001,2002,2001,2002],
        'pop': [1.5,1.7,3.6,2.4,2.9]
     }
dataDF=pd.DataFrame(data,columns=['year','state','pop','debt','gando'],index=['one','two','three','four','five'])
print (dataDF)


       year   state  pop debt gando
one    2000    Ohio  1.5  NaN   NaN
two    2001    Ohio  1.7  NaN   NaN
three  2002    Ohio  3.6  NaN   NaN
four   2001  Nevada  2.4  NaN   NaN
five   2002  Nevada  2.9  NaN   NaN


In [206]:
dataDF.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [207]:
dataDF['year']

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [214]:
dataDF['gando']='Qasim'
dataDF

year   state  pop debt  gando
one    2000    Ohio  1.5  NaN  Qasim
two    2001    Ohio  1.7  NaN  Qasim
three  2002    Ohio  3.6  NaN  Qasim
four   2001  Nevada  2.4  NaN  Qasim
five   2002  Nevada  2.9  NaN  Qasim

In [215]:
dataDF['eastern']=dataDF.state=='Ohio'
dataDF

year   state  pop debt  gando  eastern
one    2000    Ohio  1.5  NaN  Qasim     True
two    2001    Ohio  1.7  NaN  Qasim     True
three  2002    Ohio  3.6  NaN  Qasim     True
four   2001  Nevada  2.4  NaN  Qasim    False
five   2002  Nevada  2.9  NaN  Qasim    False

In [218]:
del dataDF['gando']
print (dataDF)

       year   state  pop debt  eastern
one    2000    Ohio  1.5  NaN     True
two    2001    Ohio  1.7  NaN     True
three  2002    Ohio  3.6  NaN     True
four   2001  Nevada  2.4  NaN    False
five   2002  Nevada  2.9  NaN    False


In [219]:
dataDF.T

one   two three    four    five
year     2000  2001  2002    2001    2002
state    Ohio  Ohio  Ohio  Nevada  Nevada
pop       1.5   1.7   3.6     2.4     2.9
debt      NaN   NaN   NaN     NaN     NaN
eastern  True  True  True   False   False

In [220]:
dataDF.reindex(index=['five','three','two','four','one'])

year   state  pop debt  eastern
five   2002  Nevada  2.9  NaN    False
three  2002    Ohio  3.6  NaN     True
two    2001    Ohio  1.7  NaN     True
four   2001  Nevada  2.4  NaN    False
one    2000    Ohio  1.5  NaN     True

In [221]:
f=lambda x:x-1
dataDF['year'].apply(f)

one      1999
two      2000
three    2001
four     2000
five     2001
Name: year, dtype: int64

In [222]:
dataDF.sort_values('pop')

year   state  pop debt  eastern
one    2000    Ohio  1.5  NaN     True
two    2001    Ohio  1.7  NaN     True
four   2001  Nevada  2.4  NaN    False
five   2002  Nevada  2.9  NaN    False
three  2002    Ohio  3.6  NaN     True

In [223]:
dataDF.describe()

year       pop
count     5.00000  5.000000
mean   2001.20000  2.420000
std       0.83666  0.864292
min    2000.00000  1.500000
25%    2001.00000  1.700000
50%    2001.00000  2.400000
75%    2002.00000  2.900000
max    2002.00000  3.600000

In [224]:
dataDF.sum()

year                          10006
state      OhioOhioOhioNevadaNevada
pop                            12.1
debt                              0
eastern                           3
dtype: object

In [227]:
import pandas as pd

# Create a sample DataFrame
data = {
    'region': ['North', 'South', 'North', 'West', 'South', 'North'],
    'sales': [1000, 1500, 800, 1200, 2000, 900]
}

df = pd.DataFrame(data)

# Group the data by the 'region' column
grouped = df.groupby('region')

# Calculate the total sales for each region
total_sales = grouped['sales'].sum()

print(total_sales)


region
North    2700
South    3500
West     1200
Name: sales, dtype: int64
